# Generated by Django 6.0.5 on 2026-06-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=40)),
                ("sku", models.CharField(max_length=18)),
                ("Price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("Quantity", models.IntegerField(max_length=12)),
            ],
        ),
    ]
