# Generated by Django 6.0.5 on 2026-06-04 21:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="Price",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="Quantity",
            new_name="quantity",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("ELECTRONICS", "electronics"),
                    ("FASHION", "fashion"),
                    ("GROCERY", "grocery"),
                ],
                default=django.utils.timezone.now,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
